### PR TITLE
Add possibility to use Monaco code editor

### PR DESCRIPTION
**Pull request by igorrius**
# Proposed Changes

> This PR adds a configuration that will add the ability to use the Monaco code editor. See https://nodered.org/blog/2021/07/20/version-2-0-released#monaco-text-editor

### CODE REVIEW

**Comment by frenck** [comment]
One can already configure that in their own configuration. Why would we add add-on options for this?

**Comment by igorrius** [comment]
> One can already configure that in their own configuration. Why would we add add-on options for this?

I've found a way to configure it in the addon configuration and decide to add this config through addon parameters like a theme.
If you think that it is a redundant configuration may you add a short description of how to achieve this?

**Comment by frenck** [comment]
> I've found a way to configure it in the addon configuration and decide to add this config through addon parameters like a theme.

Themes are brought in from external and specifically installed in this add-on (and has a bit of history as well, as it origins from a time when there wasn't such a thing as a theme in Node-RED).

> If you think that it is a redundant configuration may you add a short description of how to achieve this?

I think the documentation of Node-RED covers this pretty well?

**Comment by igorrius** [comment]
>I think the documentation of Node-RED covers this pretty well?

Yes you are right.
Maybe I've been not exactly correct, sorry about that. But I've looked at this problem from the common user side. There is no documentation how to change the addon configuration though HA.

**Comment by frenck** [comment]
> There is no documentation how to change the addon configuration though HA.

You don't need to change add-on configuration at all? This is about configuring Node-RED itself.

All Node-RED files are available, as normal, in the `node-red` folder that is in your Home Assistant configuration folder.

**Comment by igorrius** [comment]
>All Node-RED files are available, as normal, in the node-red folder that is in your Home Assistant configuration folder.

In my case, Home Assistant is isolated using Docker.

I've inspected a docker container with the Node-Red addon and found that I have the link to `/usr/share/hassio/homeassistant/node-red` folder with the configuration file. 
So maybe will be better to add a simple link to this way in the addon readme and this can save time for someone like me))) If you still have strongly sure that this PR is unnecessary of course)

Anyway! Thanks for your support and spent time!

**Comment by frenck** [comment]
> In my case, Home Assistant is isolated using Docker.

? That statement makes no sense.

> I've inspected a docker container with the Node-Red addon and found that I have the link to /usr/share/hassio/homeassistant/node-red folder with the configuration file.

Sounds like you are using non-standard ways to manage your system (guessing the path, probably a Supervised installation).

> So maybe will be better to add a simple link to this way in the addon readme and this can save time for someone like me))) If you still have strongly sure that this PR is unnecessary of course)

Running Home Assistant Supervised is an advanced installation method. We expect people to know exactly what they are doing. If these are questions that arise on your end, you might consider using a different installation method instead.

I'm going to friendly decline this PR, as this is not a task the add-on should fulfill, nor should we document non-default methods to manage configuration as listed above in the last response.

**Pull request closed without merging**
