### PR TITLE
Allow the use of secrets

### PR DESCRIPTION
**Pull request by tjorim**
Just trying things out for myself, no need to accept this PR if it's too ugly or hacky :wink:

Edit: not sure yet if it would even work

### CODE REVIEW

**Comment by tjorim** [comment]
I think it should work but I'm not able to test it because of some weird error in a file I didn't even touch.
```
[cont-init.d] 10-requirements.sh: executing... 
exec: fatal: unable to exec bash: No such file or directory
[cont-init.d] 10-requirements.sh: exited 111.
```

**Comment by frenck** [comment]
Thank you for this!

bitmoji

**Comment by dethpickle** [comment]
Hey guys, quick question - and forgive me, I couldn't find any info about how to use this aside from the reference in the change log.  Is that we can now use `!secret whatever` in the Hassio config text or can we now use !secret in the configuration of nodes inside node-red?  Or both?

And thanks for this!  Spreading passwords around files makes for maintenance headaches.

**Comment by frenck** [comment]
Hi there @dethpickle,

Please do not use merged PR's or GitHub issues for generic support questions.
Instead join or Discord: https://discord.me/hassioaddons
Or, check out the dedicated topic for this add-on on the Home Assistant Community forums.

Regarding your question: This only work from within the add-on configuration context (so not from within Node-RED).

**Pull request merged**
