### PR TITLE
Just a small detail..

### PR DESCRIPTION
**Pull request by arretx**
...to clarify whether or not apostrophes are needed in the YAML.  That was my first question, and I see that the editor will flag you if the YAML isn't correct, but it might save someone time and confusion in the future.

# Proposed Changes

Always looking for clarity in the manuals.  Great job on the add-on!

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by tjorim** [comment]
Thanks, it indeed follows yaml-spec now, it was json before (json is valid yaml). Not sure how long it's needed since there are plans to replace those options with UI elements.

**Comment by frenck** [comment]
Not sure how this is related to the add-on in any way.
For question about Home Assistant, please ask it on the Home Assistant Community or Discord chat.

Thanks.

**Comment by tjorim** [comment]
@frenck Not sure you noticed but it's about the add-on options, not the HA core configuration.

**Comment by frenck** [comment]
Sure, the add-on configuration problem is also not part of the add-on.

**Pull request closed without merging**
