### PR TITLE
Fix incorrect check for existing files

### PR DESCRIPTION
**Pull request by frenck**
# Proposed Changes

Fixes an issue where it checks if a directory exists, while it should check if a file exists.

related to #1736

### CODE REVIEW

**Comment by rubendediegomartinez** [comment]
All my scripts were disappeared!!! Help

**Comment by Shponzo** [comment]
All my flows are gone too... Is there something we can do?

**Comment by frenck** [comment]
@rubendediegomartinez Seems like you are in the wrong place. Just shouting things like that on a random PR, will not help, especially since there is no information either.

You might as well go outside and scream it there. 

Please check the issue tab instead, especially #1736.

../Frenck

**Comment by rubendediegomartinez** [comment]
> @rubendediegomartinez Seems like you are in the wrong place. Just shouting things like that on a random PR, will not help, especially since there is no information either.
> 
> You might as well go outside and scream it there.
> 
> Please check the issue tab instead, especially #1736.
> 
> ../Frenck

Sorry, they were my flows, not my scripts...

I will read your reference. 
Thanks

**Comment by Navaroff** [comment]
> All my scripts were disappeared!!! Help
> 
> Edited: sorry, not my scritpts, I wanted to say: my flows

The same happened to me. All flows gone and therefore my HA automations.

**Comment by frenck** [comment]
@Navaroff If you read above, you would know this comment makes no sense to place here... reading is essential, especially here: #1736

**Comment by sphinxlady** [comment]
> @Navaroff If you read above, you would know this comment makes no sense to place here... reading is essential, especially here: #1736

It does when you realize the fix doesn't actually fix the problem sadly

**Pull request merged**
